[[ $NOT_FIRST_TIME ]] || {
    # source /usr/local/opt/chruby/share/chruby/chruby.sh
    # source /usr/local/opt/chruby/share/chruby/auto.sh
    # chruby ruby-2.4.2
    eval "$(rbenv init -)"
    eval "$(goenv init -)"
    eval $(thefuck --alias)

    NOT_FIRST_TIME=1
}
export PATH="$HOME/go/bin:$PATH"
setopt no_beep
setopt no_flow_control
setopt ignore_eof
setopt interactive_comments
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt extended_glob

# My project folder
export ZGEN_RESET_ON_CHANGE=($HOME/.zshrc)

# load zgen
source "$HOME/.zgen/zgen.zsh"

if ! zgen saved; then
    zgen prezto

    # prezto options
    zgen prezto editor key-bindings 'vi'
    zgen prezto prompt theme 'pure'

    # custom
    zgen load wbinglee/zsh-wakatime
    zgen load rupa/z # cd to the most recent dir
    zgen load junegunn/fzf # Ctrl-t and Ctrl-r fzf bindings
    zgen load changyuheng/fz
    zgen load supercrabtree/k # New l

    # prezto and modules
    zgen prezto archive
    zgen prezto autosuggestions
    zgen prezto git
    zgen prezto command-not-found
    zgen prezto syntax-highlighting
    zgen prezto completion
    zgen prezto directory
    zgen prezto environment
    zgen prezto history
    zgen prezto history-substring-search
    zgen prezto osx
    zgen prezto ruby
    zgen prezto utility
    zgen prezto fasd
    zgen prezto gnu-utility
    zgen prezto homebrew
    zgen prezto rsync
    zgen prezto terminal
    zgen prezto tmux

    # generate the init script from plugins above
    zgen save
fi

export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'

# export FZF_DEFAULT_COMMAND='
#   (git ls-tree -r --name-only HEAD ||
#    fd . -path "*/\.*" -prune -o -type f -print -o -type l -print |
#       sed s/^..//) 2> /dev/null'

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='--height 40% --reverse --border --preview "head -100 {}" --bind "enter:execute(vim {})"'

# Function for safe sourcing of files
function include {
    [[ -s "$1" ]] && source "$1" || echo "$1 not loaded"
}

include $HOME/.iterm2_shell_integration.zsh

# Load custom functions
include $HOME/.zsh/functions.zsh

# Load custom aliases
include $HOME/.zsh/aliases.zsh

autoload -Uz add-zsh-hook
add-zsh-hook -D preexec _custom_check_aliases
add-zsh-hook preexec _custom_check_aliases
doing
