export DOTFILES="$HOME/.dotfiles"
export ZDOTDIR="$HOME"
export ZSH="$HOME"
export PROJECTS="$HOME/Documents/Projects"

source <(antibody init)
source ~/.antibody_bundles.zsh

include () {
    [[ -s "$1" ]] && source "$1" || echo "$1 not loaded"
}

set -G
for zshrc_snipplet in ~/.zsh/rc/*; do
    source $zshrc_snipplet
done
